begin;

drop function if exists public.sync_osoba_kontakt_dates();

drop table if exists public.historia_kontaktu cascade;
drop table if exists public.osoby cascade;
drop table if exists public.firmy cascade;
drop table if exists public.uzytkownicy cascade;
drop table if exists public.statusy_leadow cascade;
drop table if exists public.zrodla_leadow cascade;

create table public.uzytkownicy (
  id uuid primary key references auth.users(id) on delete cascade,
  utworzono_at timestamptz not null default now(),
  imie varchar(100) not null,
  nazwisko varchar(120) not null,
  email varchar(255) not null unique,
  telefon varchar(50),
  rola varchar(30) not null default 'handlowiec',
  aktywny boolean not null default true,
  constraint uzytkownicy_rola_check check (rola in ('admin', 'handlowiec'))
);

create table public.firmy (
  id bigint generated by default as identity primary key,
  utworzono_at timestamptz not null default now(),
  nazwa varchar(255) not null,
  nip varchar(20),
  strona_www varchar(255),
  wielkosc_firmy varchar(50),
  branza varchar(120),
  opis text,
  telefon varchar(50),
  email varchar(255),
  adres_ulica varchar(255),
  adres_miasto varchar(120),
  adres_kod_pocztowy varchar(20),
  adres_kraj varchar(120),
  notatki text,
  przypisany_uzytkownik_id uuid,
  constraint firmy_przypisany_uzytkownik_id_fkey
    foreign key (przypisany_uzytkownik_id)
    references public.uzytkownicy(id)
    on delete set null
);

create table public.zrodla_leadow (
  id bigint generated by default as identity primary key,
  nazwa varchar(120) not null unique
);

create table public.statusy_leadow (
  id bigint generated by default as identity primary key,
  nazwa varchar(120) not null unique,
  kolejnosc integer not null,
  zamkniety boolean not null default false
);

create table public.osoby (
  id bigint generated by default as identity primary key,
  utworzono_at timestamptz not null default now(),
  imie varchar(100) not null,
  nazwisko varchar(120) not null,
  firma_id bigint,
  telefon varchar(50),
  email varchar(255),
  zrodlo_id bigint,
  status_id bigint,
  notatki text,
  przypisany_uzytkownik_id uuid,
  ostatni_kontakt timestamptz,
  nastepny_kontakt timestamptz,
  utworzyl_uzytkownik_id uuid,
  constraint osoby_firma_id_fkey
    foreign key (firma_id)
    references public.firmy(id)
    on delete set null,
  constraint osoby_zrodlo_id_fkey
    foreign key (zrodlo_id)
    references public.zrodla_leadow(id)
    on delete set null,
  constraint osoby_status_id_fkey
    foreign key (status_id)
    references public.statusy_leadow(id)
    on delete set null,
  constraint osoby_przypisany_uzytkownik_id_fkey
    foreign key (przypisany_uzytkownik_id)
    references public.uzytkownicy(id)
    on delete set null,
  constraint osoby_utworzyl_uzytkownik_id_fkey
    foreign key (utworzyl_uzytkownik_id)
    references public.uzytkownicy(id)
    on delete set null
);

create table public.historia_kontaktu (
  id bigint generated by default as identity primary key,
  osoba_id bigint not null,
  uzytkownik_id uuid,
  typ_kontaktu varchar(40) not null,
  opis text not null,
  data_kontaktu timestamptz not null default now(),
  nastepny_kontakt timestamptz,
  constraint historia_kontaktu_osoba_id_fkey
    foreign key (osoba_id)
    references public.osoby(id)
    on delete cascade,
  constraint historia_kontaktu_uzytkownik_id_fkey
    foreign key (uzytkownik_id)
    references public.uzytkownicy(id)
    on delete set null,
  constraint historia_kontaktu_typ_kontaktu_check
    check (typ_kontaktu in ('telefon', 'email', 'spotkanie', 'inne'))
);

create index idx_firmy_przypisany_uzytkownik_id on public.firmy(przypisany_uzytkownik_id);
create index idx_osoby_firma_id on public.osoby(firma_id);
create index idx_osoby_status_id on public.osoby(status_id);
create index idx_osoby_zrodlo_id on public.osoby(zrodlo_id);
create index idx_osoby_przypisany_uzytkownik_id on public.osoby(przypisany_uzytkownik_id);
create index idx_osoby_nastepny_kontakt on public.osoby(nastepny_kontakt);
create index idx_historia_kontaktu_osoba_id on public.historia_kontaktu(osoba_id);
create index idx_historia_kontaktu_data_kontaktu on public.historia_kontaktu(data_kontaktu desc);

create function public.sync_osoba_kontakt_dates()
returns trigger
language plpgsql
as $$
begin
  update public.osoby
     set ostatni_kontakt = greatest(coalesce(ostatni_kontakt, '-infinity'::timestamptz), new.data_kontaktu),
         nastepny_kontakt = coalesce(new.nastepny_kontakt, nastepny_kontakt)
   where id = new.osoba_id;

  return new;
end;
$$;

create trigger trg_sync_osoba_kontakt_dates
after insert on public.historia_kontaktu
for each row execute function public.sync_osoba_kontakt_dates();

insert into public.statusy_leadow (id, nazwa, kolejnosc, zamkniety)
values
  (1, 'nowy', 1, false),
  (2, 'kontakt', 2, false),
  (3, 'kwalifikacja', 3, false),
  (4, 'oferta', 4, false),
  (5, 'wygrany', 5, true),
  (6, 'przegrany', 6, true);

insert into public.zrodla_leadow (nazwa)
values
  ('LinkedIn'),
  ('Formularz WWW'),
  ('Konferencja'),
  ('Cold call'),
  ('Polecenie');

alter table public.uzytkownicy enable row level security;
alter table public.firmy enable row level security;
alter table public.osoby enable row level security;
alter table public.historia_kontaktu enable row level security;
alter table public.zrodla_leadow enable row level security;
alter table public.statusy_leadow enable row level security;

create policy p_uzytkownicy_all on public.uzytkownicy
for all to authenticated
using (true)
with check (true);

create policy p_uzytkownicy_all_anon on public.uzytkownicy
for all to anon
using (true)
with check (true);

create policy p_firmy_all on public.firmy
for all to authenticated
using (true)
with check (true);

create policy p_firmy_all_anon on public.firmy
for all to anon
using (true)
with check (true);

create policy p_osoby_all on public.osoby
for all to authenticated
using (true)
with check (true);

create policy p_osoby_all_anon on public.osoby
for all to anon
using (true)
with check (true);

create policy p_historia_kontaktu_all on public.historia_kontaktu
for all to authenticated
using (true)
with check (true);

create policy p_historia_kontaktu_all_anon on public.historia_kontaktu
for all to anon
using (true)
with check (true);

create policy p_zrodla_leadow_all on public.zrodla_leadow
for all to authenticated
using (true)
with check (true);

create policy p_zrodla_leadow_all_anon on public.zrodla_leadow
for all to anon
using (true)
with check (true);

create policy p_statusy_leadow_all on public.statusy_leadow
for all to authenticated
using (true)
with check (true);

create policy p_statusy_leadow_all_anon on public.statusy_leadow
for all to anon
using (true)
with check (true);

commit;
